### PR TITLE
Drop the twoxtx feature since we now always build against a compatible monorepo

### PR DESCRIPTION
**Pull request by mvines**
Unfortunately this surfaces new test errors ⚰️

### CODE REVIEW

**Comment by mvines** [comment]
@samkim-crypto - hey, do you want to check this out?  This seems likely to be related to the recent work to add transfer fee proofs?  Unfortunately this test wasn't running in CI so it's not totally clear when this failure was first introduced

```
$ cd program/
$ cargo test -- test_transfer_self
...
running 1 test
[2022-01-06T01:39:54.170111000Z INFO  solana_program_test] "spl_zk_token" program loaded as native code
[2022-01-06T01:39:54.482627000Z DEBUG solana_runtime::message_processor::stable_log] Program ZkTokenProof1111111111111111111111111111111 invoke [1]
[2022-01-06T01:39:54.482676000Z DEBUG solana_runtime::message_processor::stable_log] VerifyTransfer
[2022-01-06T01:39:54.484356000Z DEBUG solana_runtime::message_processor::stable_log] proof verification failed: SigmaProof
[2022-01-06T01:39:54.484368000Z DEBUG solana_runtime::message_processor::stable_log] Program ZkTokenProof1111111111111111111111111111111 failed: invalid instruction data
test test_transfer_self ... FAILED
...
```

**Comment by samkim-crypto** [comment]
Okay, I can take a look!

**Comment by mvines** [comment]
cc: https://github.com/solana-labs/solana/pull/22337

**Comment by mvines** [comment]
@samkim-crypto - just checking, are you going to update zk-token program with the sdk transfer proof changes?

**Comment by samkim-crypto** [comment]
Yes, I was in the process of sending you a message. I am continuing to look into the issue. It seems like the test is failing due to the issues with ciphertext validity proof most likely from refactoring for the fee proof. solana-labs/solana#22337 does not fix the issue and I would need to look into it this afternoon. 

But simply commenting out the ciphertext validity check in the transfer verification will most likely resolve the issue immediately. What do you think?

**Comment by mvines** [comment]
Better to fix the full issue, it's fine if this test continues to fail in the meantime IMO

**Comment by samkim-crypto** [comment]
Okay, will do. I'll get it resolved by today.

**Comment by samkim-crypto** [comment]
@mvines The problem was that the test was defined with respect to the all-zero auditor public key. An ElGamal ciphertext can be an all-zero trivial ciphertext, but an ElGamal public key should always be generated at random; messages encrypted under the trivial ElGamal public key are not recoverable. Hence, the ciphertext validity verification was designed to reject proofs for any ciphertext encrypted under the trivial ElGamal pubkey (for safety).

Took a while to identify this, but all of the tests should now pass. Finally time to get lunch...

I think we should rename `ElGamalKeypair::default()` to `ElGamalKeypair::random()`. For private keys and keypairs, we use `default()` to mean randomly sampled. For others like `ElGamalPubkey::default()`, we use `default()` to mean all-zero byte values. This makes sense given that secret keys should never be all-zero bytes, but I think it would be much clearer to leave `default()` undefined for secret keys and use `random()` instead.

**Comment by mvines** [comment]
> I think we should rename ElGamalKeypair::default() to ElGamalKeypair::random().

Yep I agree, that makes much more sense!

**Comment by mvines** [comment]
`test_transfer_self` passes for me locally but fails consistently in GH CI :-/

**Comment by samkim-crypto** [comment]
I've been looking at it this morning. This definitely appears to be an async issue since the tests are sometimes succeeding and sometimes failing for me. I can't quite identify what is causing it though yet. The only real difference between `transfer` and `transfer_self` is the way source and destination accounts are assigned https://github.com/solana-labs/spl-zk-token/blob/master/program/src/processor.rs#L715. I will continue to look into the code...

**Comment by samkim-crypto** [comment]
It seems like this is actually an issue with setting the solana dependency to `1.10.0`. The problem goes away if we set it back to `1.9`.

It is an odd behavior though. I was experimenting with it a bit and wrote a minimal program to emulate the problem in case you want to take a look https://github.com/samkim-crypto/pod-test.

**Pull request closed without merging**
